### ISSUE TITLE
Pipeline - optimalizace a úprava

### ISSUE THREAD

**Issue by ornsteinfilip** [sinfin/k8s-base#6]
Je potřeba optimalizovat pipeline, aby byl co nejrychlejší čas provedení testů i deploye.

- [x] zrychlit instalaci Gemfile pomocí cache
- [ ] zrychlit kompilování assets pomocí cache(?)
- [ ] přidat tlačítko umožňující spustit seed pro review / staging prostředí

**Comment by jindrichskupa** [comment]
Kompletni pipeline je vcetne nasazeni staging a prod na cca 5 minut. Je treba jeste dale optimalizovat?

https://gitlab.com/sinfin1/notesvilla/-/pipelines/276738969

**Comment by ornsteinfilip** [comment]
@jindrichskupa Rychlost je nyni ok. Uvidime pak na narocnejsich projektech, jako je Squared. diky

**Comment by ornsteinfilip** [comment]
@jindrichskupa Zrychlil jsem runner1 na 4 dedicated CPU a k tomu paralelni bundle install. Nicmene se nam tam porad plete prj.netbrick.eu. Je mozne to vypnout, prosim? Pak bych toto issue uzavrel. diky
