### ISSUE TITLE
Grafana cloud

### ISSUE THREAD

**Issue by ornsteinfilip** [sinfin/k8s-base#8]
Rozběhnout a nasadit logování a metriky v Grafana cloud. Máme do tří uživatelů, takže free verze. Mám založit účet?

**Comment by jindrichskupa** [comment]
* [x] monitoring webu (zbyva doplnit domeny)
* [ ] logy z k8s do loki/grafana
* [ ] nastavit v prometheu, co je nasazeny jako helm remote do grafana cloudu
* [ ] zobrazit gitlab deployment/environment a dalsi statisitky
* [ ] pridat blackbox exporter + kontrolu validity certifikatu

**Comment by jindrichskupa** [comment]
Logy z clusteru jsou uz posilany do lokiho:
[priklad dotazu](https://sinfin.grafana.net/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22grafanacloud-sinfin-logs%22,%7B%22exemplar%22:true,%22expr%22:%22%7Bnamespace%3D%5C%22notesvilla-24876169-staging%5C%22%7D%20%7C%3D%20%5C%22POST%5C%22%22%7D%5D), [popis dotazovaciho jazyka](https://grafana.com/docs/loki/latest/logql/)

**Comment by ornsteinfilip** [comment]
@jindrichskupa Je potřeba přeposílat metriky z ingresu a chyby 4xx, 5xx.
