### ISSUE TITLE
Stage PostgreSQL db

### ISSUE THREAD

**Issue by ornsteinfilip** [sinfin/k8s-base#9]
Domluvil jsme se, že review prostředí si potáhnout svoji malou db k zahození (takto je nyní), ale stage budou směrovat najeden 2GB droplet s PGSQL.

**Comment by jindrichskupa** [comment]
Nastavte prosim DNS:

* [ ] `postgres1.sinfin.cz` 165.22.201.219
* [ ] `runner1.sinfin.cz` 164.90.167.185

**Comment by ornsteinfilip** [comment]
@jindrichskupa Na tyto technické domény máme doménu sinfin.io, udělal jsem tedy následovně. Může být?

```
runner1.sinfin.io. | A | 300 | 164.90.167.185
postgres1.sinfin.io. | A | 300 | 165.22.201.219
```

**Comment by jindrichskupa** [comment]
Jasne, zadny problem. Prejmenuju to v DO aby to nematlo. Diky

**Comment by ornsteinfilip** [comment]
@jindrichskupa Tohle by nám teď pomohlo nejvíce pro denní práci.

**Comment by jindrichskupa** [comment]
Pripravil jsem ansible na management postgresql databazi na dedikovanem serveru, novy ucet je mozne vytvorit analogicky: https://gitlab.com/sinfin1/infra/ansible/-/blob/master/vars/postgres1.sinfin.io.yml

**Comment by jindrichskupa** [comment]
Notesvilla i aukceaukci stage jsem mergnul a data by mela byt prenesena. Pridal jsem do Ansible readme.md jak sifrovat heslo pomoci ansible-vault.

**Comment by ornsteinfilip** [comment]
Ok, jen tedy NV stage konci 500

**Comment by ornsteinfilip** [comment]
@jindrichskupa Bohužel zůstala v AA stage db od NV a oba projekty to nějak nakoplo.

**Comment by ornsteinfilip** [comment]
@jindrichskupa Omlouvám se, ale potřeboval bych návod jako pro BFU, jak rozchodit staging db. NV a AA se v detailech liší a ansible projekt mi také moc nepomohl ;\ Nyní například nevím jak dál pro projekt `sinfindigital`. Plus mne napadá, zda by se nemohlo nějaké samo vygenerovat a uložit již při prvním deploy stagingu?
